name: PlatformIO Dependency Updater

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  platformio:
    name: PlatformIO Dependency Updater
    runs-on: ubuntu-slim

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Check for dependency updates
        uses: ./
